### ISSUE TITLE
Lifetime values spa and circulation pump seem to be wrong

### ISSUE THREAD

**Issue by npinguin** [Ylianst/ESP-IQ2020#10]
Hi 

Looks like the circulation pump total lifetime values are not correct. spa is of 2017, hotspring envoy, fw 2.02

![image](https://github.com/Ylianst/ESP-IQ2020/assets/13931779/1e6758c1-7232-4a5c-97e4-4fa83db3fbe2)

![image](https://github.com/Ylianst/ESP-IQ2020/assets/13931779/b84c5cee-bb5d-4bb3-aa60-d243b2d9fc8b)

**Comment by Ylianst** [comment]
@npinguin I am not sure there is anything I can do about this. We could look at the raw status (0x0256), you may have submitted it on a different issue? If that is the reported value in the raw command, I am not sure what correctly can be applied to it.

**Comment by npinguin** [comment]
I will update the firmware later this week to 4.05 let’s see what that brings

**Comment by Ylianst** [comment]
@npinguin Oh! Please take note of any changes. So far, this integration seems to work ok on all firmware versions, but would be nice to spot any differences.

**Comment by Ylianst** [comment]
I will close this one since I imagine there is no change and nothing we can really do about this. However, please re-open if there is any additional information.
