### ISSUE TITLE
Error while compiling / installing - adding light control

### ISSUE THREAD

**Issue by itry2fly** [Ylianst/ESP-IQ2020#12]
I am wanting to add the light control and added the extra code to my config, but am getting the following error when trying to compile, any ideas? 

![image](https://github.com/Ylianst/ESP-IQ2020/assets/15127650/68af81ff-e8c5-4b78-b033-c6ab74489b9a)

**Comment by itry2fly** [comment]
Reconfigured yaml file, compiled ok after

**Comment by Ylianst** [comment]
It's likely the `text` section was missing. You need this even if it's empty like this:

```
text:
```

That would have fixed it.
