### ISSUE TITLE
Add salt chlorine generation parameter ?

### ISSUE THREAD

**Issue by todely** [Ylianst/ESP-IQ2020#16]
Hello

Thanks for your amazing work !!
I have a request, on my hot tub i have fresh water system (generation of chlorine from salt in water). There is a level as parameter of "power" from 0 to 9.

Is it possible to get it / change it ?

Thanks !
Best Regards,

**Comment by Ylianst** [comment]
[Take a look here](https://github.com/Ylianst/ESP-IQ2020/blob/main/documentation/extras.md#ace--freshwater-salt-systems) and let me know if it works. That should give you control over the Freshwater module.

**Comment by todely** [comment]
Oh sorry i didn't read the extra part of documentation....
I works perfectly thanks !

**Comment by Ylianst** [comment]
Nice! Thanks for reporting back.
